import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const readinessTone = {
    ready: 'tone-ready',
    'needs-review': 'tone-review',
    blocked: 'tone-blocked',
};
export const ExpertTable = ({ experts, total, page, pageSize, onPageChange, onSelectExpert, selectedExpertId, }) => {
    const totalPages = Math.max(1, Math.ceil(total / pageSize));
    return (_jsxs("section", { className: "table-card", children: [_jsxs("div", { className: "table-header", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "Queue snapshot" }), _jsxs("h2", { children: [total, " experts in scope"] })] }), _jsxs("p", { className: "table-meta", children: ["Page ", page, " of ", totalPages] })] }), _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Expert" }), _jsx("th", { children: "Specialty" }), _jsx("th", { children: "Readiness" }), _jsx("th", { children: "Review flag" }), _jsx("th", { "aria-label": "Action column" })] }) }), _jsx("tbody", { children: experts.map((expert) => (_jsxs("tr", { "data-testid": `expert-row-${expert.id}`, children: [_jsxs("td", { children: [_jsx("strong", { children: expert.name }), _jsx("p", { children: expert.location }), _jsx("small", { children: expert.bioSnippet })] }), _jsx("td", { children: expert.specialty }), _jsx("td", { children: _jsx("span", { className: `pill ${readinessTone[expert.readiness]}`, children: expert.readiness }) }), _jsx("td", { children: expert.reviewFlag ? (_jsxs("div", { children: [_jsx("strong", { children: "Flagged" }), _jsx("p", { children: expert.reviewFlag.reason }), _jsx("small", { children: expert.reviewFlag.flaggedBy })] })) : (_jsx("span", { className: "muted", children: "Open" })) }), _jsx("td", { children: _jsx("button", { className: selectedExpertId === expert.id ? 'secondary-button selected' : 'secondary-button', onClick: () => onSelectExpert(expert), disabled: Boolean(expert.reviewFlag), children: expert.reviewFlag ? 'Already flagged' : 'Flag' }) })] }, expert.id))) })] }), _jsxs("div", { className: "pager", children: [_jsx("button", { className: "secondary-button", onClick: () => onPageChange(page - 1), disabled: page <= 1, children: "Previous" }), _jsx("button", { className: "secondary-button", onClick: () => onPageChange(page + 1), disabled: page >= totalPages, children: "Next" })] })] }));
};
